FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src
COPY migrations ./migrations

RUN mvn -DskipTests package

FROM eclipse-temurin:17-jre
WORKDIR /app

COPY --from=build /app/target/*.jar /app/app.jar
COPY migrations ./migrations

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
